name: FINAL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - python=3.10.12=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - appdirs==1.4.4
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - idna==3.6
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.3.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.21.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.8.1.78
      - pandas==2.0.3
      - pillow==10.0.0
      - pip==21.1.3
      - protobuf==4.25.1
      - psutil==5.9.7
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.11.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.12
      - threadpoolctl==3.2.0
      - timm==0.5.4
      - torch==2.1.2
      - torchvision==0.16.2
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - wandb==0.16.1
prefix: /home/hcis-s17/miniconda3/envs/FINAL
